"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv

# .env 파일이 있으면 그 안의 값을 os.environ으로 불러온다
# (OPENROUTER_API_KEY 같은 값을 매번 export 안 해도 되게 하기 위함)
BASE_DIR_FOR_ENV = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR_FOR_ENV / ".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 배포 환경에서는 .env(또는 클라우드타입 환경변수)에 DJANGO_SECRET_KEY를 넣어서 씀.
# 로컬 개발용 기본값은 그대로 두되, 실제 배포 시엔 반드시 다른 값으로 설정할 것.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-2#%r#79h4!8%2d1q2%d&#xrj-qn%q1n*1aw+uy(1wpd3t-s!q1",
)

# SECURITY WARNING: don't run with debug turned on in production!
# .env에 DJANGO_DEBUG=False 를 넣으면 운영 모드로 전환됨 (기본값은 로컬 개발 편의를 위해 True)
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# 클라우드타입 등에서 배포하면 도메인이 매번 달라질 수 있어서,
# .env에 ALLOWED_HOSTS=도메인1,도메인2 형태로 콤마 구분해 넣으면 그 값을 씀.
# 아무것도 안 넣으면 전부 허용(*) — 개인/가족용 소규모 프로젝트라 우선 이렇게 두되,
# 나중에 실제 배포 도메인이 정해지면 그 도메인만 넣는 걸 권장.
_allowed_hosts_env = os.environ.get("ALLOWED_HOSTS", "*")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",")]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'learning',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 프론트엔드 배포 주소를 .env에 CORS_ALLOWED_ORIGINS=https://xxx.cloudtype.app 형태로
# 넣으면 그 주소만 허용(더 안전). 안 넣으면 전체 허용 — 개인/가족용 소규모
# 프로젝트라 지금은 이렇게 두되, 나중에 실제 배포 도메인이 안정되면 위처럼
# 좁혀서 넣는 걸 권장.
_cors_env = os.environ.get("CORS_ALLOWED_ORIGINS", "")
if _cors_env:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_env.split(",")]
else:
    CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# .env에 DATABASE_URL이 있으면 그걸 씀(클라우드타입 Postgres 등),
# 없으면 로컬 개발용으로 SQLite를 그대로 씀.
import dj_database_url

_database_url = os.environ.get("DATABASE_URL")
if _database_url:
    DATABASES = {"default": dj_database_url.parse(_database_url, conn_max_age=600)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
