# Generated by Django 6.0.7 on 2026-07-16 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('chalk_color', models.CharField(default='#F2C94C', max_length=20)),
                ('semester', models.CharField(choices=[('1학기', '1학기'), ('2학기', '2학기')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_ready', models.BooleanField(default=False)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='learning.domain')),
            ],
            options={
                'ordering': ['domain__order', 'order'],
            },
        ),
    ]
